require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShippingAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # ShippingAddress. As you add validations to ShippingAddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "address_line_1" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShippingAddressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all shipping_addresses as @shipping_addresses" do
      shipping_address = ShippingAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shipping_addresses).should eq([shipping_address])
    end
  end

  describe "GET show" do
    it "assigns the requested shipping_address as @shipping_address" do
      shipping_address = ShippingAddress.create! valid_attributes
      get :show, {:id => shipping_address.to_param}, valid_session
      assigns(:shipping_address).should eq(shipping_address)
    end
  end

  describe "GET new" do
    it "assigns a new shipping_address as @shipping_address" do
      get :new, {}, valid_session
      assigns(:shipping_address).should be_a_new(ShippingAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested shipping_address as @shipping_address" do
      shipping_address = ShippingAddress.create! valid_attributes
      get :edit, {:id => shipping_address.to_param}, valid_session
      assigns(:shipping_address).should eq(shipping_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShippingAddress" do
        expect {
          post :create, {:shipping_address => valid_attributes}, valid_session
        }.to change(ShippingAddress, :count).by(1)
      end

      it "assigns a newly created shipping_address as @shipping_address" do
        post :create, {:shipping_address => valid_attributes}, valid_session
        assigns(:shipping_address).should be_a(ShippingAddress)
        assigns(:shipping_address).should be_persisted
      end

      it "redirects to the created shipping_address" do
        post :create, {:shipping_address => valid_attributes}, valid_session
        response.should redirect_to(ShippingAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shipping_address as @shipping_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingAddress.any_instance.stub(:save).and_return(false)
        post :create, {:shipping_address => { "address_line_1" => "invalid value" }}, valid_session
        assigns(:shipping_address).should be_a_new(ShippingAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingAddress.any_instance.stub(:save).and_return(false)
        post :create, {:shipping_address => { "address_line_1" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shipping_address" do
        shipping_address = ShippingAddress.create! valid_attributes
        # Assuming there are no other shipping_addresses in the database, this
        # specifies that the ShippingAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShippingAddress.any_instance.should_receive(:update_attributes).with({ "address_line_1" => "MyString" })
        put :update, {:id => shipping_address.to_param, :shipping_address => { "address_line_1" => "MyString" }}, valid_session
      end

      it "assigns the requested shipping_address as @shipping_address" do
        shipping_address = ShippingAddress.create! valid_attributes
        put :update, {:id => shipping_address.to_param, :shipping_address => valid_attributes}, valid_session
        assigns(:shipping_address).should eq(shipping_address)
      end

      it "redirects to the shipping_address" do
        shipping_address = ShippingAddress.create! valid_attributes
        put :update, {:id => shipping_address.to_param, :shipping_address => valid_attributes}, valid_session
        response.should redirect_to(shipping_address)
      end
    end

    describe "with invalid params" do
      it "assigns the shipping_address as @shipping_address" do
        shipping_address = ShippingAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipping_address.to_param, :shipping_address => { "address_line_1" => "invalid value" }}, valid_session
        assigns(:shipping_address).should eq(shipping_address)
      end

      it "re-renders the 'edit' template" do
        shipping_address = ShippingAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShippingAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => shipping_address.to_param, :shipping_address => { "address_line_1" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shipping_address" do
      shipping_address = ShippingAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => shipping_address.to_param}, valid_session
      }.to change(ShippingAddress, :count).by(-1)
    end

    it "redirects to the shipping_addresses list" do
      shipping_address = ShippingAddress.create! valid_attributes
      delete :destroy, {:id => shipping_address.to_param}, valid_session
      response.should redirect_to(shipping_addresses_url)
    end
  end

end
